config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end 
  resources :films do
    resource :favorites, only: [:create, :destroy]
  end
  get "favorite_posts" => "favorites#favorite_posts"
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :film

    validates_uniqueness_of :film_id, scope: :user_id
end

app/models/film.rb
class Film < ApplicationRecord  
    belongs_to :user
    has_many :favorites, dependent: :destroy
    belongs_to :genre

    with_options presence: true do
      validates :title
      validates :story
      validates :filmdirector
      validates :origin
      validates :releasedate
      validates :country
      validates :starring
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :films 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :films, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :nickname, presence: true
  
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  def already_favorited?(film)
    self.favorites.exists?(film_id: film.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:nickname])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        @favorite = current_user.favorites.create(film_id: params[:film_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @film = Film.find(params[:film_id])
        @favorite = current_user.favorites.find_by(film_id: @film.id)
        @favorite.destroy
        redirect_back(fallback_location: root_path)
    end

    def favorite_posts
        @films = Film.Includes(:favorites).where(user_id: current_user.id)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @films = Film.all
  end

  def show
    @film = Film.find(params[:id])
  end

  def new
    @film = Film.new
    @genres = Genre.all
  end

  def create
    @film = Film.new(film_params)
    @film.user_id = current_user.id
    @film.genre_id = params[:genre][:id]
    if @film.save
      redirect_to film_path(@film), notice: "投稿に成功しました。"
    else
      flash[:alret] = @film.errors.full_messages
      @film.errors.full_messages
      render :new
    end
  end

  def edit
    @film = Film.find(params[:id])
    @genres = Genre.all
    if @film.user != current_user
      redirect_to films_path, alert: '不正なアクセスです。'
    end 
  end

  def update
    @film = Film.find(params[:id])
    if @film.update(film_params)
      redirect_to film_path(@film), notice: "更新に成功しました。"
    else
      render :edit
    end
  end

  private
  def film_params
    params.require(:film).permit(:title, :story, :filmdirector, :origin, :releasedate, :country, :starring, :name, :genre_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :authenticate_user!
    def create
        following = current_user.relationships.build(follower_id: params[:user_id])
        following.save
        redirect_to request.referrer || root_path
    end

    def destroy
        following = current_user.relationships.find_by(follower_id: params[:user_id])
        following.destroy
        redirect_to request.referrer || root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
    @login_users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @films_registered_as_favorites = Film.includes(:favorites).where(user_id: current_user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新に成功しました。"
    else
      render :edit
    end
  end
  
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/films/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        映画編集
      </h1>
    </div>
  </div>
</section>

<% if @film.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@film.errors.count, "error") %> 保存されていません</h2>
    <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>  
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @film do |f| %>
            <div class="field">
                <%= f.label :title, "タイトル", class: "label" %>
                <%= f.text_field :title %>
            </div>

            <div class="field">
                <%= f.label :story, "あらすじ", class: "label" %>
                <%= f.text_area :story %>
            </div>

            <div class="field">
                <%= f.label :filmdirector, "映画監督", class: "label" %>
                <%= f.text_field :filmdirector %> 
            </div>

            <div class="field">
                <%= f.label :origin, "原作", class: "label" %>
                <%= f.text_field :origin %>
            </div>

            <div class="field">
                <%= f.label :releasedate, "公開日", class: "label" %>
                <%= f.text_field :releasedate %>
            </div>

            <div class="field">
                <%= f.label :starring,"主演", class: "label" %>
                <%= f.text_field :starring %>
            </div>

            <div class="field">
                <%= f.label :country,"製作国", class: "label" %>
                <%= f.text_field :country %>
            </div>

            <div class="field">
                <%= fields_for :genre ,(@genre) do |genre| %>
                    <%= genre.label:type, "ジャンル", class: "label" %>
                    <%= genre.collection_select :id, Genre.all, :id, :name %>
                <% end %>
            </div>

        <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/films/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        映画一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @films.each do |film| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to film.user.name, user_path(film.user) %></div> 
                    <%= link_to film_path(film) do %> 
                      <div class="title"><%= film.title %></div>
                    <% end %>
                  <div class="content"><time><%= film.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新</div>
                  <div>
                    <% if current_user.already_favorited?(film) %>
                      <%= button_to 'お気に入りを外す', film_favorites_path(film.id), method: :delete %>
                    <% else %>
                      <%= button_to 'お気に入り', film_favorites_path(film) %>
                    <% end %>
                  </div> 
                </div>
              </div>    
            </div>      
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/films/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        映画情報投稿
      </h1>
    </div>
  </div>
</section>

<% if @film.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@film.errors.count, "error") %> 保存されていません。</h2>
    <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>  
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @film do |f| %>

          <div class="field">  
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title %>
          </div>
          
          <div class="field">
            <%= f.label :story, "あらすじ", class: "label" %>
            <%= f.text_area :story %>
          </div>

          <div class="field">
            <%= f.label :filmdirector, "監督", class: "label" %>
            <%= f.text_field :filmdirector %>
          </div>

          <div class="field">
            <%= f.label :origin, "原作", class: "label" %>
            <%= f.text_field :origin %>
          </div>

          <div class="field">
            <%= f.label :releasedate, "公開日", class: "label" %>
            <%= f.text_field :releasedate %>
          </div>

          <div class="field">
            <%= f.label :country, "製作国", class: "label" %>
            <%= f.text_field :country %>
          </div>

          <div class="field">
            <%= f.label :starring, "主演", class: "label" %>
            <%= f.text_field :starring %>
          </div>
          
          <div class="field">
            <%= fields_for :genre ,(@genre) do |genre| %>
              <%= genre.label:type, "ジャンル", class: "label" %>
              <%= genre.collection_select :id, Genre.all, :id, :name %>
            <% end %>    
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
        
      </div>
    </div>
  </div>
</section>

app/views/films/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        映画情報
      </h1>
      <h1 class="title"> 
        投稿者 
      </h1> 
      <%= link_to user_path(@film.user), class: "panel-block" do %>
        <span class="panel-icon">
          <i class="fas fa-user" aria-hidden="true"></i>
        </span>
       <p class="title is-4">
         <%= @film.user.name %> さんのページへ
       </p>
      <% end %>
    </div>
  </div>
</section>

<div class="card-content">
 <div class="media">
  <div class="media-content">
   <h1 class="title"> タイトル </h1>

    <p class="title is-4"><%= @film.title %></p>
   <h1 class="title"> あらすじ </h1>

    <p class="title is-4"><%= @film.story %></p>
   <h1 class="title"> 映画監督 </h1>

    <p class="title is-4"><%= @film.filmdirector %></p>
   <h1 class="title"> 原作 </h1>

    <p class="title is-4"><%= @film.origin %></p>
   <h1 class="title"> 公開日 </h1>

    <p class="title is-4"><%= @film.releasedate %></p>
   <h1 class="title"> 主演 </h1>
    <p class="title is-4"><%= @film.starring %></p>
   <h1 class="title"> 製作国 </h1>

    <p class="title is-4"><%= @film.country %></p>
   <h1 class="title"> ジャンル </h1>
   
    <p class="title is-4"><%= @film.genre.name %></p> 
  </div>
 </div>
</div>




<% if @film.user.id == current_user.id %>
  <%= link_to "編集画面へ", edit_film_path(@film), class: "button is-success" %>
<% end %>

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">recipegram</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EigaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
  </head>

  <body>

    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <div class="notification is-danger">
     <%= flash[:alret] %>
    </div>
    
    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">eigaapp</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
          </div>
            <div class="navbar-end">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "映画投稿一覧", films_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ユーザー一覧", users_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "映画新規投稿", new_film_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "映画投稿一覧", films_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ユーザー一覧", users_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<section class="hero is-success">
 <div class="hero-body">
  <div class="container">
    <h1 class="title">
      ユーザー編集
    </h1>
  </div>
 </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> 保存されていません</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>  
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
       <%= form_for @user do |f| %>

         <div class="field">
          <%= f.label :name, "ユーザー名", class: "label" %>
          <%= f.text_field :name, class: "input" %>
         </div>

         <div class="field">
          <%= f.label :nickname, "ニックネーム", class: "label" %>
          <%= f.text_field :nickname, class: "input" %>
         </div>

         <div class="field">
          <%= f.label :email, "メールアドレス", class: "label" %>
          <%= f.email_field :email, class: "input" %>
         </div>
  
         <%= f.submit "更新", class: "button is-success" %>

       <% end %>

      </div>
    </div>
  </div>
</section>    

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.name, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.films.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
            <table class="table is-fullwidth">
                <tr>
                    <td class="is-size-4">
                      名前

                      <strong><%= @user.name %></strong>
                    </td>
                    <% if @user.id == current_user.id %>
                     <td class="is-size-4">
                       メールアドレス

                       <strong><%= @user.email %></strong>
                     </td>
                     <td class="is-size-4">
                       ニックネーム

                       <strong><%= @user.nickname %></strong>
                     </td>
                     <td>
                     </td>
                     <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                    <% end %>
                     お気に入り投稿一覧
                    <% @films_registered_as_favorites.each do |films_registered_as_favorite| %>
                     <%= films_registered_as_favorite.title %>
                    <% end %>
                </tr>
            </table> 
        </div>
      </div>
    </div>
  </div>
</section>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <svg width="80" height="80" class="svg-icon" viewBox="0 0 20 20">
        <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
      </svg>
      <h1 class="fw-light"><%= @user.name %></h1>
      <p class="text-small"><%= link_to @user.followings.count, followings_user_path(@user) %> フォロー <%= link_to @user.followers.count, followers_user_path(@user) %> フォロワー</p>
      <% if @user == current_user %>
        <p class="lead text-muted">You're currently signed in as <%= current_user.email %></p>
      <% else %>
        <% if @user.is_followed_by?(current_user) %>
          <%= "フォロー解除ボタン" %>
          <%=button_to user_relationships_path(@user), method: :delete do %>
          <% end %>
        <% else %>
          <%= "フォローボタン" %>
          <%=button_to user_relationships_path(@user), method: :post do %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>